language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBootProject
  - mkdir -p deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mv SpringBootProject.zip deploy/SpringBootProject.zip
  -
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      #The value that was set on Travis repository
    secret_access_key: $AWS_SECRET_KEY  #The value that was set on Travis repository
    bucket: freelect-springboot-bild #AWS S3's bucket name
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                        #Make access license about Zip file to private
    local_dir: deploy                   #The directory that was created in before_deploy
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      sooji7876@gmail.com